apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-aggregator
  namespace: journal-system
  labels:
    component: log-management
spec:
  selector:
    matchLabels:
      task: log-aggregation
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        task: log-aggregation
    spec:
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      containers:
      - name: aggregation-engine
        image: alpine:3.17.2
        command:
        - /bin/ash
        - "-o"
        - "pipefail"
        - "-c"
        - |
          apk update && \
          apk add --no-cache curl jq && \
          apk add --no-cache nano && \
          apk del nano
          
          DATA_DIR="/var/lib/logdata"
          mkdir -p "${DATA_DIR}"
          
          INTERVAL=85
          ENDPOINT="http://journal-api-service.journal-system/entries"
          
          while :; do
            TIMESTAMP=$(date +'%Y-%m-%dT%H:%M:%S')
            echo "${TIMESTAMP} [INFO] Starting aggregation cycle..."
            
            curl -sS "${ENDPOINT}" -o "${DATA_DIR}/aggregated_${TIMESTAMP}.log"
            
            echo "Current log snapshot:"
            printf '=%.0s' {1..45}
            echo
            tail -n 5 "${DATA_DIR}/aggregated_${TIMESTAMP}.log"
            printf '=%.0s' {1..45}
            echo
            
            sleep $((INTERVAL + 5))
          done
        volumeMounts:
        - name: aggregation-volume
          mountPath: /var/lib/logdata
          readOnly: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: aggregation-volume
        emptyDir:
          sizeLimit: 1Gi