apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  namespace: journal-system
  labels:
    app: journal-api
spec:
  selector:
    app: journal-api
    role: prod
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
  sessionAffinity: None 